### ISSUE TITLE
Error with pytest==4.1.0

### ISSUE THREAD

**Issue by joshbode** [ionelmc/pytest-benchmark#141]
Hello,

I've just upgraded to `pytest==4.1.0` today and I'm getting an error with `pytest-benchmark==3.1.1`:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/_pytest/main.py", line 199, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/_pytest/config/__init__.py", line 636, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pluggy/hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pytest_benchmark/plugin.py", line 427, in pytest_configure
INTERNALERROR>     bs = config._benchmarksession = BenchmarkSession(config)
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pytest_benchmark/session.py", line 31, in __init__
INTERNALERROR>     self.logger = Logger(self.verbose, config)
INTERNALERROR>   File "/Users/josh/.virtualenvs/default/lib/python3.7/site-packages/pytest_benchmark/logger.py", line 16, in __init__
INTERNALERROR>     self.pytest_warn = config.warn
INTERNALERROR> AttributeError: 'Config' object has no attribute 'warn'
```

If I downgrade back to `pytest==4.0.2` there is no error.

I'm on Python 3.7 on macOS

**Comment by joshbode** [comment]
Looks like this may be the cause: pytest-dev/pytest/issues/3078

**Comment by chrahunt** [comment]
This error is mentioned in #124 and already fixed pending a new release of pytest-benchmark.

**Comment by joshbode** [comment]
Oops - sorry, didn't see that one - closing

**Comment by ionelmc** [comment]
3.2.0 was just released.
