### ISSUE TITLE
Stuck with errors related to % sign for --benchmark-compare-fail

### ISSUE THREAD

**Issue by trubesv** [ionelmc/pytest-benchmark#176]
Hello, first of all thanks for this great tool :)

I am stuck in a kind of deadlock situation I can't seem to resolve, maybe I am missing something obvious.

For instance I have the following:
```
# setup.cfg
[tool:pytest]
addopts = --benchmark-compare-fail=min:6%
```
Naturally it works fine with `pytest`.

Trouble comes when I run `pip install <something>` in a directory containing that file:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/trubesv/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/trubesv/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 253, in run
    options.use_user_site = decide_user_install(
  File "/home/trubesv/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 604, in decide_user_install
    if site_packages_writable(root=root_path, isolated=isolated_mode):
  File "/home/trubesv/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 549, in site_packages_writable
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "/home/trubesv/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 543, in get_lib_location_guesses
    scheme = distutils_scheme('', *args, **kwargs)
  File "/home/trubesv/.local/lib/python3.8/site-packages/pip/_internal/locations.py", line 109, in distutils_scheme
    d.parse_config_files()
  File "/usr/lib/python3.8/distutils/dist.py", line 413, in parse_config_files
    val = parser.get(section,opt)
  File "/usr/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'
```
This seems fine according to the python "configfile" spec.

After adding another `%` as suggested, `pip install` succeed but by running `pytest`, I got:
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --benchmark-compare-fail: Could not parse value: 'min:6%%'
```
So now I am stuck in a state where I can't install requirements or I can't run tests :(

Is there a quick fix I can use/implement on my side?
Is this a `pytest-benchmark` issue or a `pytest` one?
Should it be escalated as a `pip` issue maybe?

Thanks for your time :)

**Comment by trubesv** [comment]
Just got sent this by a colleague:
https://docs.pytest.org/en/latest/customize.html#setup-cfg

Tried with a `pytest.ini` file and it works, so I am closing this :)
