### ISSUE TITLE
Client failing to initialize in Python 3.12

### ISSUE THREAD

**Issue by ricardoV94** [ionelmc/pytest-benchmark#263]
```python
py.test-benchmark
Traceback (most recent call last):
  File "/home/.../bin/py.test-benchmark", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/.../lib/python3.12/site-packages/pytest_benchmark/cli.py", line 143, in main
    hook = HookDispatch(mode=args.importmode, root=pathlib.Path('.'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.12/site-packages/pytest_benchmark/cli.py", line 125, in __init__
    self.conftest = pathlib.import_path(conftest_file, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: import_path() missing 1 required keyword-only argument: 'consider_namespace_packages'
```

**Comment by cryptix** [comment]
I'm seeing this on 3.11.9, too.
