### ISSUE TITLE
Issue with Xdist plugin: impossibile to serialize

### ISSUE THREAD

**Issue by JayZar21** [ionelmc/pytest-benchmark#7]
I have different test written with pytest-benchmark. I use also the Xdist plugin to distribute my test on more than a process.
Starting py.test with Xdist run gives this output:

```
py.test -n 2
 ============================= test session starts =============================
platform win32 -- Python 2.7.3 -- py-1.4.26 -- pytest-2.6.4
plugins: benchmark, xdist
gw0 C / gw1 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\main.py", line 82,
in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\core.py", line 413,
 in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\core.py", line 424,
 in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\core.py", line 315,
 in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "C:\Python27\lib\site-packages\xdist\dsession.py", line 48
0, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)

INTERNALERROR>   File "C:\Python27\lib\site-packages\xdist\slavemanage.py", line
 45, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "C:\Python27\lib\site-packages\xdist\slavemanage.py", line
 54, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "C:\Python27\lib\site-packages\xdist\slavemanage.py", line
 223, in setup
INTERNALERROR>     self.channel.send((self.slaveinput, args, option_dict))
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 681, in send
INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_inter
nal(item))
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1285, in dumps_internal
INTERNALERROR>     return _Serializer().save(obj)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1303, in save
INTERNALERROR>     self._save(obj)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1321, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1402, in save_tuple
INTERNALERROR>     self._save(item)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1321, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1398, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1392, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File "C:\Python27\lib\site-packages\execnet\gateway_base.py", l
ine 1319, in _save
INTERNALERROR>     raise DumpError("can't serialize %s" % (tp,))
INTERNALERROR> DumpError: can't serialize <class 'pytest_benchmark.plugin.NameWr
apper'>
```

**Comment by ionelmc** [comment]
I'm doing some work in the develop branch for this.

**Comment by JayZar21** [comment]
Thank you!

**Comment by untitaker** [comment]
Does it even make sense to benchmark when other processes might interfere with the results?

**Comment by ionelmc** [comment]
Not really, but people keep asking for this. Bad results and big warning is less worse than completely broken.

**Comment by JayZar21** [comment]
Yes, benchmark make little sense mixed with other tests.
The problem is that "py.test src -n 2  --benchmark-skip" gives the error reported above.
So even skipping benchmarks I'm not able to use run my full tests in more than 1 process.

**Comment by ionelmc** [comment]
Would it be acceptable for you if benchmarks are skipped automatically if you use xdist?

**Comment by JayZar21** [comment]
Yes, I think this is a good tradeoff.
However I suppose that someone could like to run only benchmarks with xdist on multiple processes.
I don't know if this is possible, but it can be an option for a future development.

**Comment by ionelmc** [comment]
It's fixed now in master. It will automatically disable (skip) benchmarks if xdist is active and print out a big fat red warning.

**Comment by untitaker** [comment]
The big red warning is not there anymore. I have a testsuite where I run everything with `--boxed` by default, with the result that benchmark output is silently missing.
