### ISSUE TITLE
KeyError: 'ops' with pytest-benchmark compare

### ISSUE THREAD

**Issue by The-Compiler** [ionelmc/pytest-benchmark#81]
I only have one saved benchmark currently, which is written by 3.0.0: 
[0001_x.json.txt](https://github.com/ionelmc/pytest-benchmark/files/1170147/0001_x.json.txt) (renamed so I can upload it here)

When I do `pytest-benchmark compare` with 3.1.0, I get:

```
Computing stats ...Traceback (most recent call last):
  File "./.tox/py36/bin/pytest-benchmark", line 11, in <module>
    sys.exit(main())
  File "/home/florian/proj/qutebrowser/git/.tox/py36/lib/python3.6/site-packages/pytest_benchmark/cli.py", line 162, in main
    results_table.display(TerminalReporter(), groups, progress_reporter=report_noprogress)
  File "/home/florian/proj/qutebrowser/git/.tox/py36/lib/python3.6/site-packages/pytest_benchmark/table.py", line 39, in display
    benchmarks, tr, "{line} ({pos}/{total})", line=line))
  File "/home/florian/proj/qutebrowser/git/.tox/py36/lib/python3.6/site-packages/pytest_benchmark/table.py", line 38, in <genexpr>
    worst[prop] = min(bench[prop] for _, bench in progress_reporter(
KeyError: 'ops'
```

**Comment by ionelmc** [comment]
Released `3.1.1`.
